trainingInput:
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: epoch_acc
    maxTrials: 4
    maxParallelTrials: 2
    params:
    - parameterName: batch_size
      type: INTEGER
      minValue: 100
      maxValue: 102
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: learning_rate
      type: DOUBLE
      minValue: 0.01
      maxValue: 0.1
      scaleType: UNIT_LOG_SCALE
